version: '3.7'

services:
  mysql:
    image: mysql:8.0
    networks:
      - network_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`mysql.igr.org.br`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3306"    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      replicas: 1

  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - network_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`phpmyadmin.igr.org.br`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"    
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    deploy:
      replicas: 1

networks:
  network_public:
    external: true

volumes:
  mysql_data: